name: Build OsmAnd~ Plus version (Arm64)
on:
  schedule:
    - cron: '40 18 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout OsmAnd
      uses: actions/checkout@v3
      with:
        path: android
    - name: checkout OsmAnd-resources
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources
    - name: checkout OsmAnd-core
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: checkout OsmAnd-core-legacy
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: checkout OsmAnd-build
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: checkout OsmAnd-tools
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-tools
        path: tools
    - name: checkout OsmAnd-misc
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-misc
        path: misc

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x gradlew
    - name: Patch memory requirements
      working-directory: ./android
      run: printf "\norg.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8\n" >> gradle.properties
    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assembleandroidFullLegacyArm64Release
    - name: Make output dir
      working-directory: ./
      run: mkdir src
    - name: Rename APK
      working-directory: ./android
      run: mv /home/runner/work/OsmAnd-BackLocManifest/OsmAnd-BackLocManifest/android/OsmAnd/build/outputs/apk/androidFullLegacyArm64/release/OsmAnd-androidFull-legacy-arm64-release.apk /home/runner/work/OsmAnd-BackLocManifest/OsmAnd-BackLocManifest/src/osm-arm64.apk
    - name: Upload Release
      uses: CrazyGunman2C4U/nightly-release-NoDel@main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FSYNC }}
      with:
        tag_name: auto-release
        name: 'OsmAnd~ Background Location Fix Fork Arm64 Release $$'
        prerelease: false
        body: 'Check https://osmand.net/blog for news. (Arm64-only!)'
        files: |
          ./*.apk
          osm-arm64.apk
          /home/runner/work/OsmAnd-BackLocManifest/OsmAnd-BackLocManifest/src/osm-arm64.apk
