name: Build Full OsmAnd~ version; could be used for F-Droid builds. Doesn't use GooglePlay services.

on:
  schedule:
    - cron: '48 18 * * 4'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout OsmAnd
      uses: actions/checkout@v3
      with:
        path: android
    - name: checkout OsmAnd-resources
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources
    - name: checkout OsmAnd-core
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: checkout OsmAnd-core-legacy
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: checkout OsmAnd-build
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: checkout OsmAnd-tools
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-tools
        path: tools
    - name: checkout OsmAnd-misc
      uses: actions/checkout@v3
      with:
        repository: osmandapp/OsmAnd-misc
        path: misc

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x gradlew
    - name: Patch memory requirements
      working-directory: ./android
      run: printf "\norg.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8\n" >> gradle.properties
    - name: Build with Gradle https://osmand.net/docs/technical/build-osmand/how-to-compile-the-android-version
      working-directory: ./android
      run: ./gradlew assembleandroidFullLegacyArm64Release
    - name: Rename APK
      working-directory: ./android
      run: mv OsmAnd/build/outputs/apk/androidFullLegacyArm64/release/OsmAnd-androidFull-legacy-arm64-release.apk OsmAnd/build/outputs/apk/androidFullLegacyArm64/release/OsmAnd-androidFull-legacy-arm64-release-$(git log -n 1 --format='%h').apk
    - name: Archive APK
      uses: actions/upload-artifact@v3
      with:
        name: osm
        path: android/OsmAnd/build/outputs/apk/*/*/*.apk
        retention-days: 90
