name: Sync Fork

on:
  schedule:
    - cron: '40 18 * * 4'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: CrazyGunman2C4U
          repo: OsmAnd-BackLocManifest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ github.token }}
          merge_method: merge
          base: master
          head: master
