name: Sync Fork

on:
  schedule:
    - cron: '40 18 * * 4'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: CrazyGunman2C4U
          repo: OsmAnd-BackLocManifest
          token: ${{ github.token }}
          base: master
          head: master
